### PR TITLE
Issue/13

### PR DESCRIPTION
**Pull request by KeithWoods**

### CODE REVIEW

**Comment by KeithWoods** [comment]
Merge if your happy @JakeGinnivan :)

**Comment by JakeGinnivan** [comment]
Will check it later, out atm

Sent from my Windows Phone
________________________________

**Comment by KeithWoods** [comment]
If you don't mind I might just merge this in as I have another for held events that I'd like to push and release before I jump on a plan

**Comment by JakeGinnivan** [comment]
:+1:

**Pull request merged**
